# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.branch}}
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - run: ./gradlew --continue | exit 1
        if: always()
      - uses: vishnudxb/cancel-workflow@v1.2
        if: failure()
        with:
          repo: czarmayne/employee-monitoring
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}
        
  build2:
    name: Build 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      continue-on-error: false
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - uses: vishnudxb/cancel-workflow@v1.2
      if: failure()
      with:
        repo: czarmayne/employee-monitoring
        workflow_id: ${{ github.run_id }}
        access_token: ${{ github.token }}
        
  # should not exec since there is cancel workflow job      
  
  build3:
    name: Build 3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - run: exit 1
    - uses: vishnudxb/cancel-workflow@v1.2
      if: failure()
      with:
        repo: czarmayne/employee-monitoring
        workflow_id: ${{ github.run_id }}
        access_token: ${{ github.token }}
  
  build4:
    name: Build 4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - run: exit 1
    - uses: vishnudxb/cancel-workflow@v1.2
      if: failure()
      with:
        repo: czarmayne/employee-monitoring
        workflow_id: ${{ github.run_id }}
        access_token: ${{ github.token }}
        
  values:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Input Value
        run: echo 'PR = "${{github.event.pull_request.number}}" ,State = "${{github.event.review.state}}" ,User = "${{github.actor}}" ,Event Name = "${{github.event_name}}" '
  job-2:
    name: Run job2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "running job2"
