name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        description: "input name"
        required: true
        type: string
      condition:
        description: "input name"
        required: true
        type: boolean
        default: true
      branch:
        description: 'Enter the branch to run unit tests from'
        required: true
        default: 'main'
        type: string

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: "Echo Output"
        run: echo "${{ github.event.inputs.branch }} ${{ github.ref }} ${GITHUB_REF##*/} =========${{ inputs.condition }} ${{ inputs.username }}"
      - if: ${{ inputs.condition}}
        name: "Greet the user"
        run: echo "Hello ${{ inputs.username }}"
# name: Reusable workflow

# on:
#   workflow_call:
#     # Map the workflow outputs to job outputs
#     outputs:
#       firstword:
#         description: "The first output string"
#         value: ${{ jobs.example_job.outputs.output1 }}
#       secondword:
#         description: "The second output string"
#         value: ${{ jobs.example_job.outputs.output2 }}

# jobs:
#   example_job:
#     name: Generate output
#     runs-on: ubuntu-latest
#     # Map the job outputs to step outputs
#     outputs:
#       output1: ${{ steps.step1.outputs.firstword }}
#       output2: ${{ steps.step2.outputs.secondword }}
#     steps:
#       - id: step1
#         run: echo "::set-output name=firstword::hello"
#       - id: step2
#         run: echo "::set-output name=secondword::world"