name: Get Previous Previous Commit Changes

on:
  workflow_dispatch:

jobs:
  getPreviousPreviousChanges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Previous Previous Commit Changes
        id: previousPreviousChanges
        run: |
          PREVIOUS_COMMIT_SHA=$(git log | grep 'commit' | tail -n 2 | sed -n '$-1p' | awk -F"commit" '{print $2}')
          echo "::set-output name=previous_commit_sha::$PREVIOUS_COMMIT_SHA"

      - name: Print Previous Commit SHA
        run: |
          echo "Previous Commit SHA: ${{ steps.previousPreviousChanges.outputs.previous_commit_sha }}"

      - name: Check Diff with Previous Previous Commit
        run: |
          git --no-pager diff --name-only ${{ steps.previousPreviousChanges.outputs.previous_commit_sha }} ${{ github.sha }} | sort -u
